### ISSUE TITLE
Some Missing Things for Blood DPS

### ISSUE THREAD

**Issue by Serverfrog** [Hellixoid/BistooltipAddon#2]
Yes i know, that special guy is here again ;)
I found some Bugs with the Blood DPS (some are also here https://github.com/Hellixoid/BistooltipAddon/issues/1#issuecomment-1757680822  but i will list them Again)

- Tooltip does not show BloodDPS
- Preraid States Darkmoon Card: greatness as BiS2, but Non-Hero Death's Verdic would be in its place

The first thing is really a bummer, the second is rather a nice-to-have

**Comment by Serverfrog** [comment]
Furthermore BiS 5 on Chests are the Shoulderplates.
Should be Scourgelord Battleplate but it is Scourgelord Shoulderplates

**Comment by Hellixoid** [comment]
Tooltip now should correctly show BDPS spec.
Regarding Preraid items, all bis data is collected automatically by a python script. And I don't want to create any differences between the data shown in my addon and the data source web page. So that's why it won't be fixed until wowhead authors update their data.
